spring:
  application:
    name: phantom-server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/234687552/phantom
          username: 234687552@qq.com
          password: lzd3860875
          default-label: master
          search-paths: '{application}-conf'
#http://localhost:7005/phantom-service-provider/master
server:
  port: 7005


eureka:
  auth:
    user: kingboy
    password: 123456
  client:
    service-url:
      #TODO 生产环境中配置高可用 http://${eureka.auth.user}:${eureka.auth.password}@localhost:7001/eureka/,http://${eureka.auth.user}:${eureka.auth.password}@localhost:7002/eureka/
      defaultZone: http://${eureka.auth.user}:${eureka.auth.password}@localhost:7000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

security:
  user:
    name: kingboy
    password: 123456

