spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/provider?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#更改使用log4jdbc 来使参数打印出来   参考http://blog.csdn.net/blueheart20/article/details/52382052
    driver-class-name: net.sf.log4jdbc.DriverSpy
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 30
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    data: classpath:data.sql
info:
  app:
    name: ${spring.application.name}
management:
  security:
    enabled: false